import {
  DailySummarySchema,
  MeetingSummarySchema,
  type DailySummary,
  type LoadedMeetingNote,
  type MeetingSummary
} from "@meeting-copilot/contracts";

export interface RenderedMeetingExport {
  documentHtml: string;
  fragmentHtml: string;
  plainText: string;
}

export function renderMeetingExport(note: LoadedMeetingNote): RenderedMeetingExport {
  if (!note.structuredResult) {
    throw new Error("This meeting does not have structured AI data available for export");
  }
  const portuguese = note.language.startsWith("pt");
  const reportBody =
    note.meetingType === "daily"
      ? renderDaily(DailySummarySchema.parse(note.structuredResult), portuguese)
      : renderGeneral(MeetingSummarySchema.parse(note.structuredResult), portuguese);
  const metadata = renderMetadata(note, portuguese);
  const body = `
    <main class="meeting-report">
      <header class="report-header">
        <div class="brand-row">
          <span class="brand-mark">M</span>
          <span>Meeting Copilot</span>
        </div>
        <p class="report-type">${
          note.meetingType === "daily"
            ? portuguese
              ? "RELATÓRIO DE DAILY"
              : "DAILY STATUS REPORT"
            : portuguese
              ? "ATA DE REUNIÃO"
              : "MEETING NOTES"
        }</p>
        <h1>${escapeHtml(note.structuredResult.title)}</h1>
        ${metadata}
      </header>
      ${reportBody}
      <footer>
        <span>${portuguese ? "Gerado pelo Meeting Copilot" : "Generated by Meeting Copilot"}</span>
        <span>${escapeHtml(formatExportDate(new Date(), portuguese))}</span>
      </footer>
    </main>`;
  const styles = exportStyles();
  return {
    documentHtml: `<!doctype html>
<html lang="${portuguese ? "pt-BR" : "en"}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(note.structuredResult.title)}</title>
  <style>${styles}</style>
</head>
<body>${body}</body>
</html>`,
    fragmentHtml: `<style>${styles}</style>${body}`,
    plainText:
      note.meetingType === "daily"
        ? renderDailyText(DailySummarySchema.parse(note.structuredResult), note, portuguese)
        : renderGeneralText(MeetingSummarySchema.parse(note.structuredResult), note, portuguese)
  };
}

function renderMetadata(note: LoadedMeetingNote, portuguese: boolean): string {
  const items = [
    note.meetingName ? `${portuguese ? "Reunião" : "Meeting"}: ${note.meetingName}` : null,
    note.meetingDate
      ? `${portuguese ? "Data" : "Date"}: ${formatMeetingDate(note.meetingDate, portuguese)}`
      : `${portuguese ? "Início" : "Started"}: ${formatDateTime(note.startedAt, portuguese)}`,
    `${portuguese ? "Duração" : "Duration"}: ${formatDuration(note.startedAt, note.endedAt)}`
  ].filter((value): value is string => Boolean(value));
  return `<div class="metadata">${items
    .map((item) => `<span>${escapeHtml(item)}</span>`)
    .join("")}</div>`;
}

function renderGeneral(summary: MeetingSummary, portuguese: boolean): string {
  return `
    <section class="overview-card">
      <p class="section-label">${portuguese ? "VISÃO GERAL" : "OVERVIEW"}</p>
      <p>${escapeHtml(summary.overview)}</p>
    </section>
    ${renderActionItems(summary, portuguese)}
    ${renderDecisions(summary, portuguese)}
    ${renderTopics(summary, portuguese)}
    <div class="two-column">
      ${renderStringSection(portuguese ? "Próximos passos" : "Next steps", summary.next_steps)}
      ${renderStringSection(
        portuguese ? "Questões em aberto" : "Open questions",
        summary.open_questions
      )}
    </div>`;
}

function renderActionItems(summary: MeetingSummary, portuguese: boolean): string {
  if (!summary.action_items.length) return "";
  return `<section class="report-section">
    <div class="section-heading">
      <span class="section-number">${String(summary.action_items.length).padStart(2, "0")}</span>
      <h2>${portuguese ? "Tarefas e responsáveis" : "Action items"}</h2>
    </div>
    <div class="action-grid">
      ${summary.action_items
        .map(
          (item) => `<article class="action-card">
            <span class="checkbox"></span>
            <div>
              <h3>${escapeHtml(item.task)}</h3>
              <div class="action-meta">
                <span><b>${portuguese ? "Responsável" : "Owner"}:</b> ${escapeHtml(
                  item.owner || (portuguese ? "Não definido" : "Not assigned")
                )}</span>
                <span><b>${portuguese ? "Prazo" : "Due"}:</b> ${escapeHtml(
                  item.due_date || (portuguese ? "Não definido" : "Not defined")
                )}</span>
                <span class="priority priority-${item.priority}">${escapeHtml(
                  priorityLabel(item.priority, portuguese)
                )}</span>
              </div>
            </div>
          </article>`
        )
        .join("")}
    </div>
  </section>`;
}

function renderDecisions(summary: MeetingSummary, portuguese: boolean): string {
  if (!summary.decisions.length) return "";
  return `<section class="report-section">
    <div class="section-heading"><h2>${portuguese ? "Decisões" : "Decisions"}</h2></div>
    <div class="decision-list">
      ${summary.decisions
        .map(
          (item) => `<article>
            <span class="decision-mark">✓</span>
            <div><h3>${escapeHtml(item.decision)}</h3>${
              item.context ? `<p>${escapeHtml(item.context)}</p>` : ""
            }</div>
          </article>`
        )
        .join("")}
    </div>
  </section>`;
}

function renderTopics(summary: MeetingSummary, portuguese: boolean): string {
  if (!summary.key_topics.length) return "";
  return `<section class="report-section">
    <div class="section-heading"><h2>${portuguese ? "Principais tópicos" : "Key topics"}</h2></div>
    <div class="topic-grid">
      ${summary.key_topics
        .map(
          (item, index) => `<article>
            <span>${String(index + 1).padStart(2, "0")}</span>
            <h3>${escapeHtml(item.topic)}</h3>
            <p>${escapeHtml(item.summary)}</p>
          </article>`
        )
        .join("")}
    </div>
  </section>`;
}

function renderDaily(summary: DailySummary, portuguese: boolean): string {
  return `
    <section class="overview-card">
      <p class="section-label">${portuguese ? "STATUS GERAL DO TIME" : "TEAM STATUS"}</p>
      <p>${escapeHtml(summary.overview)}</p>
    </section>
    <section class="report-section">
      <div class="section-heading">
        <span class="section-number">${String(summary.participant_updates.length).padStart(2, "0")}</span>
        <h2>${portuguese ? "Atualizações individuais" : "Participant updates"}</h2>
      </div>
      <div class="participant-list">
        ${summary.participant_updates
          .map((update) => renderParticipant(update, portuguese))
          .join("")}
      </div>
    </section>
    <div class="two-column">
      ${renderStringSection(
        portuguese ? "Bloqueios do time" : "Team blockers",
        summary.team_blockers,
        "warning"
      )}
      ${renderStringSection(
        portuguese ? "Próximos passos do time" : "Team next steps",
        summary.team_next_steps
      )}
      ${renderStringSection(
        portuguese ? "Participantes ausentes" : "Absent participants",
        summary.absent_participants
      )}
    </div>
    ${renderUnresolved(summary, portuguese)}`;
}

function renderParticipant(
  update: DailySummary["participant_updates"][number],
  portuguese: boolean
): string {
  const participant =
    update.participant ||
    (portuguese ? "Participante não identificado" : "Unidentified participant");
  return `<article class="participant-card">
    <header>
      <span class="avatar">${escapeHtml(participant.slice(0, 1).toUpperCase() || "?")}</span>
      <div><h3>${escapeHtml(participant)}</h3><p>${escapeHtml(update.summary)}</p></div>
      <span class="confidence confidence-${update.attribution_confidence}">${escapeHtml(
        confidenceLabel(update.attribution_confidence, portuguese)
      )}</span>
    </header>
    <div class="status-grid">
      ${renderCompactList(portuguese ? "Concluído" : "Completed", update.completed, "success")}
      ${renderCompactList(
        portuguese ? "Em andamento" : "In progress",
        update.in_progress,
        "progress"
      )}
      ${renderCompactList(portuguese ? "Bloqueios" : "Blockers", update.blockers, "danger")}
      ${renderCompactList(portuguese ? "Próximos passos" : "Next steps", update.next_steps, "next")}
    </div>
    ${
      update.dependencies.length
        ? `<div class="dependencies"><h4>${portuguese ? "DEPENDÊNCIAS" : "DEPENDENCIES"}</h4>${update.dependencies
            .map(
              (item) =>
                `<div><b>${portuguese ? "Aguardando" : "Waiting for"}: ${escapeHtml(
                  item.person_or_team || (portuguese ? "Não informado" : "Not specified")
                )}</b><span>${escapeHtml(item.dependency)}</span></div>`
            )
            .join("")}</div>`
        : ""
    }
  </article>`;
}

function renderCompactList(
  title: string,
  items: string[],
  tone: "success" | "progress" | "danger" | "next"
): string {
  if (!items.length) return "";
  return `<section class="compact-list tone-${tone}"><h4>${escapeHtml(title)}</h4><ul>${items
    .map((item) => `<li>${escapeHtml(item)}</li>`)
    .join("")}</ul></section>`;
}

function renderStringSection(title: string, items: string[], className = ""): string {
  if (!items.length) return "";
  return `<section class="list-card ${className}"><h2>${escapeHtml(title)}</h2><ul>${items
    .map((item) => `<li>${escapeHtml(item)}</li>`)
    .join("")}</ul></section>`;
}

function renderUnresolved(summary: DailySummary, portuguese: boolean): string {
  if (!summary.unresolved_attributions.length) return "";
  return `<section class="report-section unresolved">
    <div class="section-heading"><h2>${
      portuguese ? "Atribuições não resolvidas" : "Unresolved attributions"
    }</h2></div>
    ${summary.unresolved_attributions
      .map(
        (item) =>
          `<article><p>${escapeHtml(item.summary)}</p>${
            item.possible_participants.length
              ? `<small>${portuguese ? "Possíveis participantes" : "Possible participants"}: ${escapeHtml(
                  item.possible_participants.join(", ")
                )}</small>`
              : ""
          }</article>`
      )
      .join("")}
  </section>`;
}

function renderGeneralText(
  summary: MeetingSummary,
  note: LoadedMeetingNote,
  portuguese: boolean
): string {
  const sections = [summary.title, metadataText(note, portuguese), "", summary.overview];
  appendTextItems(
    sections,
    portuguese ? "TAREFAS" : "ACTION ITEMS",
    summary.action_items.map((item) => {
      const owner = item.owner || (portuguese ? "Sem responsável" : "Unassigned");
      const due = item.due_date || (portuguese ? "Sem prazo" : "No due date");
      return `${item.task} — ${owner}; ${due}; ${priorityLabel(item.priority, portuguese)}`;
    })
  );
  appendTextItems(
    sections,
    portuguese ? "DECISÕES" : "DECISIONS",
    summary.decisions.map((item) => `${item.decision}${item.context ? ` — ${item.context}` : ""}`)
  );
  appendTextItems(
    sections,
    portuguese ? "PRINCIPAIS TÓPICOS" : "KEY TOPICS",
    summary.key_topics.map((item) => `${item.topic}: ${item.summary}`)
  );
  appendTextItems(sections, portuguese ? "PRÓXIMOS PASSOS" : "NEXT STEPS", summary.next_steps);
  appendTextItems(
    sections,
    portuguese ? "QUESTÕES EM ABERTO" : "OPEN QUESTIONS",
    summary.open_questions
  );
  return sections.join("\n");
}

function renderDailyText(
  summary: DailySummary,
  note: LoadedMeetingNote,
  portuguese: boolean
): string {
  const sections = [summary.title, metadataText(note, portuguese), "", summary.overview];
  for (const update of summary.participant_updates) {
    sections.push(
      "",
      update.participant ||
        (portuguese ? "Participante não identificado" : "Unidentified participant")
    );
    sections.push(update.summary);
    appendTextItems(sections, portuguese ? "Concluído" : "Completed", update.completed);
    appendTextItems(sections, portuguese ? "Em andamento" : "In progress", update.in_progress);
    appendTextItems(sections, portuguese ? "Bloqueios" : "Blockers", update.blockers);
    appendTextItems(
      sections,
      portuguese ? "Dependências" : "Dependencies",
      update.dependencies.map(
        (item) =>
          `${portuguese ? "Aguardando" : "Waiting for"} ${item.person_or_team}: ${item.dependency}`
      )
    );
    appendTextItems(sections, portuguese ? "Próximos passos" : "Next steps", update.next_steps);
  }
  appendTextItems(
    sections,
    portuguese ? "BLOQUEIOS DO TIME" : "TEAM BLOCKERS",
    summary.team_blockers
  );
  appendTextItems(
    sections,
    portuguese ? "PRÓXIMOS PASSOS DO TIME" : "TEAM NEXT STEPS",
    summary.team_next_steps
  );
  appendTextItems(
    sections,
    portuguese ? "PARTICIPANTES AUSENTES" : "ABSENT PARTICIPANTS",
    summary.absent_participants
  );
  appendTextItems(
    sections,
    portuguese ? "ATRIBUIÇÕES NÃO RESOLVIDAS" : "UNRESOLVED ATTRIBUTIONS",
    summary.unresolved_attributions.map((item) => {
      const possibleParticipants = item.possible_participants.length
        ? ` (${portuguese ? "possíveis participantes" : "possible participants"}: ${item.possible_participants.join(", ")})`
        : "";
      return `${item.summary}${possibleParticipants}`;
    })
  );
  return sections.join("\n");
}

function appendTextItems(sections: string[], title: string, items: string[]): void {
  if (!items.length) return;
  sections.push("", title, ...items.map((item) => `• ${item}`));
}

function metadataText(note: LoadedMeetingNote, portuguese: boolean): string {
  return [
    note.meetingName ? `${portuguese ? "Reunião" : "Meeting"}: ${note.meetingName}` : null,
    `${portuguese ? "Início" : "Started"}: ${formatDateTime(note.startedAt, portuguese)}`,
    `${portuguese ? "Duração" : "Duration"}: ${formatDuration(note.startedAt, note.endedAt)}`
  ]
    .filter(Boolean)
    .join(" · ");
}

function priorityLabel(priority: "high" | "medium" | "low", portuguese: boolean): string {
  if (!portuguese) return priority;
  return { high: "prioridade alta", medium: "prioridade média", low: "prioridade baixa" }[priority];
}

function confidenceLabel(confidence: "high" | "medium" | "low", portuguese: boolean): string {
  if (!portuguese) return `${confidence} confidence`;
  return { high: "alta confiança", medium: "média confiança", low: "baixa confiança" }[confidence];
}

function formatDuration(startedAt: string, endedAt: string): string {
  const milliseconds = Math.max(0, Date.parse(endedAt) - Date.parse(startedAt));
  const totalMinutes = Math.max(1, Math.round(milliseconds / 60_000));
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  return hours ? `${hours}h ${String(minutes).padStart(2, "0")}min` : `${minutes}min`;
}

function formatDateTime(value: string, portuguese: boolean): string {
  return new Intl.DateTimeFormat(portuguese ? "pt-BR" : "en", {
    dateStyle: "medium",
    timeStyle: "short"
  }).format(new Date(value));
}

function formatMeetingDate(value: string, portuguese: boolean): string {
  const date = /^\d{4}-\d{2}-\d{2}$/.test(value) ? new Date(`${value}T12:00:00`) : new Date(value);
  return Number.isNaN(date.getTime())
    ? value
    : new Intl.DateTimeFormat(portuguese ? "pt-BR" : "en", { dateStyle: "long" }).format(date);
}

function formatExportDate(value: Date, portuguese: boolean): string {
  return new Intl.DateTimeFormat(portuguese ? "pt-BR" : "en", {
    dateStyle: "medium"
  }).format(value);
}

function escapeHtml(value: string): string {
  return value.replace(
    /[&<>"']/g,
    (character) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character] ??
      character
  );
}

function exportStyles(): string {
  return `
    :root { color: #172033; background: #eef2f6; font-family: Inter, "Segoe UI", Arial, sans-serif; }
    * { box-sizing: border-box; }
    @page { size: A4; margin: 14mm; }
    body { margin: 0; background: #eef2f6; color: #172033; font-size: 10.5pt; line-height: 1.55; }
    .meeting-report { width: min(100%, 920px); margin: 24px auto; padding: 42px 46px 30px; background: #fff; }
    .report-header { padding-bottom: 24px; border-bottom: 2px solid #e4e9ef; }
    .brand-row { display: flex; align-items: center; gap: 8px; color: #314359; font-size: 10px; font-weight: 700; }
    .brand-mark { display: grid; place-items: center; width: 22px; height: 22px; border-radius: 7px; color: #fff; background: #168a76; }
    .report-type, .section-label { margin: 24px 0 7px; color: #168a76; font-size: 9px; font-weight: 800; letter-spacing: .16em; }
    h1 { max-width: 760px; margin: 0; color: #101827; font-size: 30px; line-height: 1.14; letter-spacing: -.035em; }
    .metadata { display: flex; flex-wrap: wrap; gap: 7px; margin-top: 17px; }
    .metadata span { padding: 5px 9px; border: 1px solid #dce3ea; border-radius: 999px; color: #52647a; font-size: 9px; }
    .overview-card { margin: 24px 0; padding: 20px 22px; border: 1px solid #cfe6e1; border-left: 4px solid #1b9a84; border-radius: 10px; background: #f4fbf9; }
    .overview-card .section-label { margin: 0 0 7px; }
    .overview-card > p:last-child { margin: 0; color: #304156; font-size: 12px; line-height: 1.65; }
    .report-section { margin-top: 27px; }
    .section-heading { display: flex; align-items: center; gap: 10px; margin-bottom: 12px; }
    .section-heading h2, .list-card h2 { margin: 0; color: #172033; font-size: 15px; }
    .section-number { display: grid; place-items: center; min-width: 25px; height: 25px; border-radius: 7px; color: #168a76; background: #e6f5f2; font-size: 8px; font-weight: 800; }
    .action-grid, .participant-list { display: grid; gap: 9px; }
    .action-card { display: grid; grid-template-columns: auto 1fr; gap: 11px; padding: 13px 14px; border: 1px solid #dce3ea; border-radius: 9px; break-inside: avoid; }
    .checkbox { width: 15px; height: 15px; margin-top: 2px; border: 1.5px solid #8fa0b5; border-radius: 4px; }
    h3 { margin: 0; color: #243247; font-size: 11px; }
    .action-meta { display: flex; flex-wrap: wrap; gap: 8px 14px; margin-top: 5px; color: #66788d; font-size: 8.5px; }
    .priority, .confidence { padding: 2px 6px; border-radius: 999px; font-size: 7px; font-weight: 800; text-transform: uppercase; }
    .priority-high, .confidence-low { color: #a93043; background: #fdecef; }
    .priority-medium, .confidence-medium { color: #8a6218; background: #fff5dc; }
    .priority-low, .confidence-high { color: #137360; background: #e6f5f2; }
    .decision-list { display: grid; gap: 8px; }
    .decision-list article { display: grid; grid-template-columns: auto 1fr; gap: 10px; padding: 11px 13px; border-radius: 8px; background: #f5f7fa; break-inside: avoid; }
    .decision-mark { color: #168a76; font-weight: 900; }
    .decision-list p, .topic-grid p { margin: 3px 0 0; color: #66788d; font-size: 9.5px; }
    .topic-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px; }
    .topic-grid article { padding: 14px; border: 1px solid #e0e6ed; border-radius: 9px; break-inside: avoid; }
    .topic-grid article > span { color: #168a76; font-size: 8px; font-weight: 800; }
    .topic-grid h3 { margin-top: 5px; }
    .two-column { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px; margin-top: 24px; }
    .list-card { padding: 15px 16px; border: 1px solid #e0e6ed; border-radius: 9px; break-inside: avoid; }
    .list-card.warning { border-color: #f1d7a8; background: #fffaf0; }
    ul { margin: 8px 0 0; padding-left: 17px; }
    li { margin: 4px 0; color: #485b71; }
    .participant-card { padding: 16px; border: 1px solid #dce3ea; border-radius: 11px; break-inside: avoid; }
    .participant-card > header { display: grid; grid-template-columns: auto 1fr auto; align-items: start; gap: 10px; }
    .participant-card header p { margin: 3px 0 0; color: #66788d; font-size: 9.5px; }
    .avatar { display: grid; place-items: center; width: 31px; height: 31px; border-radius: 9px; color: #fff; background: #168a76; font-size: 10px; font-weight: 800; }
    .status-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 8px; margin-top: 12px; }
    .compact-list { padding: 10px 11px; border-left: 3px solid #8fa0b5; border-radius: 6px; background: #f6f8fa; }
    .compact-list h4, .dependencies h4 { margin: 0; color: #607287; font-size: 7.5px; letter-spacing: .08em; }
    .compact-list ul { margin-top: 5px; font-size: 8.8px; }
    .tone-success { border-left-color: #1b9a84; }
    .tone-progress, .tone-next { border-left-color: #4d7fc3; }
    .tone-danger { border-left-color: #cf5266; }
    .dependencies { margin-top: 9px; padding: 11px; border-radius: 7px; background: #fff8e8; }
    .dependencies > div { display: grid; grid-template-columns: minmax(120px, .42fr) 1fr; gap: 8px; margin-top: 6px; color: #66532e; font-size: 8.8px; }
    .unresolved article { padding: 10px 12px; border: 1px dashed #b9c4d0; border-radius: 7px; }
    .unresolved p { margin: 0; }
    .unresolved small { color: #6d7e91; }
    footer { display: flex; justify-content: space-between; margin-top: 32px; padding-top: 13px; border-top: 1px solid #e2e7ed; color: #8a99aa; font-size: 7.5px; }
    @media print {
      body { background: #fff; }
      .meeting-report { width: auto; margin: 0; padding: 0; }
    }
    @media (max-width: 680px) {
      .meeting-report { margin: 0; padding: 24px; }
      .two-column, .topic-grid, .status-grid { grid-template-columns: 1fr; }
    }`;
}
